INSERT INTO `t_platform_system_config` VALUES ('deploy.p2p.host','192.168.139.213',1,'部署：p2p服务的主机');
INSERT INTO `t_platform_system_config` VALUES ('deploy.p2p.port','8200',1,'部署：p2p服务的端口');
INSERT INTO `t_platform_system_config` VALUES ('deploy.upnp.url','http://192.168.139.213:8090/',1,'部署：upnp服务的url地址');
INSERT INTO `t_platform_system_config` VALUES ('deploy.command.srv.host','192.168.139.213',1,'部署：指令中心服务的主机');
INSERT INTO `t_platform_system_config` VALUES ('deploy.command.srv.port','26800',1,'部署：指令中心服务的端口');
INSERT INTO `t_platform_system_config` VALUES ('aws.s3.credential.key','AKIAPBNSWXDWU543KAMQ',1,'亚马逊：s3服务凭证-key');
INSERT INTO `t_platform_system_config` VALUES ('aws.s3.credential.secret','iwO4oXWUCw2I0s7wRUsAdOUFipXq8WIaNkvZqZev',1,'亚马逊：s3服务凭证-secret');
INSERT INTO `t_platform_system_config` VALUES ('aws.s3.region','CN_NORTH_1',1,'亚马逊：s3的region, BJ:CN_NORTH_1,SG:AP_SOUTHEAST_1,USA:US_WEST_1');
INSERT INTO `t_platform_system_config` VALUES ('aws.sns.credential.key','AKIAPBNSWXDWU543KAMQ',1,'亚马逊：sns服务凭证-key');
INSERT INTO `t_platform_system_config` VALUES ('aws.sns.credential.secret','iwO4oXWUCw2I0s7wRUsAdOUFipXq8WIaNkvZqZev',1,'亚马逊：sns服务凭证-secret');
INSERT INTO `t_platform_system_config` VALUES ('aws.sns.endpoint','https://sns.ap-southeast-1.amazonaws.com',1,'亚马逊：sns的endpoint');
INSERT INTO `t_platform_system_config` VALUES ('aws.s3.ip','s3.skylightsz.com',1,'亚马逊：S3服务ip地址');
INSERT INTO `t_platform_system_config` VALUES ('aws.s3.port','80',1,'亚马逊：S3服务ip端口');
INSERT INTO `t_platform_system_config` VALUES ('aws.s3.bucket','skl-developer',1,'亚马逊：S3服务存储桶');
INSERT INTO `t_platform_system_config` VALUES ('aws.s3.expire.millis','86400000',1,'亚马逊：S3服务文件失效时间');
INSERT INTO `t_platform_system_config` VALUES ('third.account.url.google','https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=',1,'第三方合作账户：服务器地址-google');
INSERT INTO `t_platform_system_config` VALUES ('third.account.url.facebook','https://graph.facebook.com/me?access_token=',1,'第三方合作账户：服务器地址-facebook');
INSERT INTO `t_platform_system_config` VALUES ('third.account.connect.timeout','10000',1,'第三方合作账户：https连接超时时间');
INSERT INTO `t_platform_system_config` VALUES ('third.account.read.timeout','10000',1,'第三方合作账户：https读取数据超时');
INSERT INTO `t_platform_system_config` VALUES ('wechat.link.url','http://wechatdev.sky-light.com.hk/front/wechat/ipcMedia/shareId',1,'微信：分享连接地址');
INSERT INTO `t_platform_system_config` VALUES ('stream.actual.access.num','10',1,'流服务：实际访问数');
INSERT INTO `t_platform_system_config` VALUES ('stream.max.relay.num','10',1,'流服务：最大relay数');
INSERT INTO `t_platform_system_config` VALUES ('stream.allow.p2p.relay','1',1,'流服务：是否允许p2p relay。# 1: not allow  0:allow');
INSERT INTO `t_platform_system_config` VALUES ('stream.relay.up.loop.times','10',1,'流服务：relay的循环次数');
INSERT INTO `t_platform_system_config` VALUES ('mes.imp_filePath','/usr/cloud/MES/MES_IMP',1,'MES：厂线上传的原始MES文件目录');
INSERT INTO `t_platform_system_config` VALUES ('mes.error_data_filePath','/usr/cloud/MES/MES_IMP/Attachment/',1,'MES：导入中有问题的数据保存的文件目录');
INSERT INTO `t_platform_system_config` VALUES ('mes.fail_import_filePath','/usr/cloud/MES/MES_IMP/Failure',1,'MES：导入失败的原始MES文件存放目录');
INSERT INTO `t_platform_system_config` VALUES ('mes.mail.receiver','wangming@sky-light.com.hk',1,'MES：接受MES导入消息的管理员邮箱');
